apiVersion: v1
kind: Pod
metadata:
  name: kubernetes-tutorial
spec:
  containers:
    - name: kubernetes-tutorial
      image: kubernetes-tutorial:latest
      imagePullPolicy: Never
      ports:
        - containerPort: 8080
          name: http-web-svc
