apiVersion: v1
kind: Service
metadata:
  name: tutorial-service
spec:
  selector:
    #app: kubernetes-tutorial
    app: kubernetes-tutorial-deployment
  ports:
    - name: name-of-service-port
      protocol: TCP
      port: 8080
      targetPort: http-web-svc
  type: NodePort
